builders:
  repository:
    import: "package:room_generator/room_generator.dart"
    builder_factories: [ "crudRepositoryBuilder" ]
    build_extensions: { ".dart": [ "crud_repository.g.part" ] }
    auto_apply: dependents
    build_to: cache
    applies_builders: [ "source_gen|combining_builder" ]
  database:
    import: "package:room_generator/room_generator.dart"
    builder_factories: [ "databaseBuilder" ]
    build_extensions: { ".dart": [ "database.g.part" ] }
    auto_apply: dependents
    build_to: cache
    applies_builders: [ "source_gen|combining_builder" ]
  entity:
    import: "package:room_generator/room_generator.dart"
    builder_factories: [ "entityBuilder" ]
    build_extensions: { ".dart": [ "table.g.part" ] }
    auto_apply: dependents
    build_to: cache
    applies_builders: [ "source_gen|combining_builder" ]